### ISSUE TITLE
Base URLs with paths are not handled

### ISSUE THREAD

**Issue by djonesCenterEdge** [CenterEdge/Yardarm#12]
When the generated code uses `client.send.async(message)` the Uri becomes invalid.  For example the URI is https://someUrl.com/somepath/ , and the Uri path being built in the requests are like /dostuff. The end result  URI is https://someUrl.com/dostuffinstead of https://someUrl.com/somepath/dostuff. The documentation for this behavior is https://tools.ietf.org/html/rfc3986#section-5.2.3.

**Comment by brantburnett** [comment]
Closed by #11
