### ISSUE TITLE
Difficult/Cumbersome Mock Testing

### ISSUE THREAD

**Issue by mmmasent** [CenterEdge/Yardarm#14]
When performing mock testing, the current sdks that are generated do not allow for easy testing. The generated response classes (created, ok, bad request, conflict, etc.) require an HttpResponseMessage and ITypeSerializerRegistry to be created and passed into the constructor.

As an example:
![image](https://user-images.githubusercontent.com/29384916/107886655-361ba880-6ecf-11eb-85cd-3bdf6094258c.png)

This makes for a cumbersome test experience since a valid HttpResponseMessage will need to be generated for every mock setup.

One option might be to use the response interfaces to create helper classes, i.e., in the example above, the `CreateUserAccountCreatedResponse` implements the `ICreateUserAccountResponse` which is the generic response all the underlying responses implement. The client will return this interface for the create call, so all one would need to do is create a fake `ICreateUserAccountResponse` test implementation. This, however, adds class complexity when testing. As an api grows, all response interfaces will be used for mock testing, meaning there will be a test implementation per response type (i.e. ICreateUserAccountResponse, IUpdateUserAccountResponse, IDeletedUserAccountResponse, etc.). 

Ideally, one would simply need to create a test object that wraps the test value to return. So, no HttpResponseMessage and type serializer objects are needed.

**Comment by brantburnett** [comment]
Duplicates #77
