### ISSUE TITLE
SDK doesn't properly handle strings with "date" format specifier

### ISSUE THREAD

**Issue by djonesCenterEdge** [CenterEdge/Yardarm#147]
When using a LocalDate type on DTOs  the generated client uses datetimes. When the client is used, the datetime values keep the timestamp, this causes a parsing error when the api server receives the request. OpenAPI appears to be handing this by chopping off the time stamp using a special converter.

**Comment by jdbrown27** [comment]
Only possible thing I have to add is  this is the OpenApiDateConverter Class

using Newtonsoft.Json.Converters;

```
namespace AdvantageApi.Client.Client
{
    /// <summary>
    /// Formatter for 'date' openapi formats ss defined by full-date - RFC3339
    /// see https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#data-types
    /// </summary>
    public class OpenAPIDateConverter : IsoDateTimeConverter
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OpenAPIDateConverter" /> class.
        /// </summary>
        public OpenAPIDateConverter()
        {
            // full-date   = date-fullyear "-" date-month "-" date-mday
            DateTimeFormat = "yyyy-MM-dd";
        }
    }
}
```

**Comment by brantburnett** [comment]
To clarify this issue a bit, the use of NodaTime.LocalDate on the server side isn't specifically relevant to Yardarm. More precisely, Yardarm-generated clients do not correctly handle the `date` string format and always serialize them as if they are `date-time`. This applies to both Newtonsoft.Json and System.Text.Json cases.
