### ISSUE TITLE
Is it possible to include ad-hoc classes in the Yardarm project?

### ISSUE THREAD

**Issue by rikrak** [CenterEdge/Yardarm#198]
More of a question that an issue:

I'm trialling the use of Yardarm in our project as I like the concept.  I've added a simple C# class to the project, but it doesn't seem to be included in the generated DLL (inspected with JetBrains DotPeek).  Is this sort of thing supported?

Here's my .csproj file:
```
<Project Sdk="Yardarm.Sdk/0.3.6">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<JsonMode>Newtonsoft.Json</JsonMode>
		<DependencyInjectionMode>Microsoft.Extensions.Http</DependencyInjectionMode>
		<AssemblyName>MyApi.Sdk</AssemblyName>
		<RootNamespace>MyApi.Sdk</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Include="Trial.cs" />
	</ItemGroup>

	<ItemGroup>
		<OpenApiSpec Include="../MyApi/swagger.json" />
	</ItemGroup>

</Project>
```

and `Trial.cs` looks like this
```
namespace MyApi.Sdk
{
    public class Trial
    {
        public static int GetInt() => 23;
    }
}
```

**Comment by brantburnett** [comment]
Currently, it isn't possible.  The only way to add classes is by adding a Yardarm extension that adds the classes. Yardarm started as a standalone generator, the SDK approach is newer and was originally just for better MSBuild integration for large projects.

However, this isn't a bad idea. The main thing I'd want to think about, if supported, would be Intellisense support. If you're adding additional bits, like extension methods, you'd want Visual Studio to not give you red squiggles for all the references to bits being generated by Yardarm. So tying into VS via source generators would be necessary, I think.

**Comment by rikrak** [comment]
Thanks for the reply.  Yes I think Source generators would have to be the way to go - I'd assumed that was what Yardarm was already using :-D  I guess not?

**Comment by brantburnett** [comment]
The amount of code being generated in some cases is a bit much for source generators. Some very large APIs are taking 20-30 seconds currently (all told including compilation though). More importantly, we actually want to use source generators on the generated source, it's very meta. 😄 For example, I'm currently working on running System.Text.Json source generators against the generated models so the generated SDKs can be AOT compatible.

**Comment by rikrak** [comment]
Cool!
Thanks for the feedback
