### ISSUE TITLE
Masked Errors

### ISSUE THREAD

**Issue by mmmasent** [CenterEdge/Yardarm#6]
Errors from api responses seem to get masked; though I've not deeply investigated it, it seems the yardarm client returns only the api documented error response.

For example, if the api spec shows the following example documented error code:
```
                "example": {
                  "errorCode": "400.",
                  "messages": [
                    "Bad Request"
                  ]
                }
```

No matter what the actual 400 response is (bad id/missing field/etc.), the yardarm client will only return the documented example string, which in the above example is `Bad Request`

**Comment by brantburnett** [comment]
I believe this was covered in my response to #10
